spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: data-to-kafka-service
          uri: lb://data-to-kafka-service
          predicates:
            - Path=/data-to-kafka-service/**
          filters:
            - RewritePath=/data-to-kafka-service/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
