spring:
  application:
    name: data-to-cassandra-service
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    username: user
    password: Pa55word
    url: r2dbc:postgresql://localhost:5433/petswave
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
  kafka:
    bootstrap-servers: localhost:2182
    consumer:
      group-id: groupId
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            value:
              default:
                type: wave.pets.data.to.cassandra.MessageEventDTO
            use:
              type:
                headers: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: '*'

server:
  port: 8088

petswave:
  kafka:
    consumer:
      topic: data
