spring:
  application:
    name: data-projector-service
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    username: user
    password: Pa55word
    url: r2dbc:postgresql://localhost:5433/petswave
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
  kafka:
    bootstrap-servers: localhost:2182
    consumer:
      group-id: groupId
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: "wave.pets.utilities.event"

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

petswave:
  kafka:
    consumer:
      topic:
        message: data
        user: user
        pet: pet
        collar: collar
