spring:
  application:
    name: data-to-kafka-service
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    local-datacenter: "datacenter1"
    keyspace-name: "petswave"
  kafka:
    bootstrap-servers: localhost:2182
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  show-actuator: true
  use-management-port: true

management:
  server:
    port: 9087
  endpoints:
    web:
      exposure:
        exclude: openapi, swagger-ui

server:
  port: 8087

petswave:
  kafka:
    producer:
      user:
        topic: user
        key: usr
      pet:
        topic: pet
        key: pt
      collar:
        topic: collar
        key: cl
      message:
        topic: data
        key: ms
