spring:
  application:
    name: query-service
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    username: user
    password: Pa55word
    url: r2dbc:postgresql://localhost:5433/petswave
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30

server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
