spring:
  application:
    name: query-service
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    username: user
    password: Pa55word
    url: r2dbc:postgresql://localhost:5433/petswave
    hostname: localhost
    database: petswave
    port: 5433

server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
